name: RPE_Segmentation
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - vc=14.2
  - vs2015_runtime
  - swig
  - pip:
    - numpy==1.23
    - tk
    - scikit-image
    - imageio
    - imagecodecs
    - pycocotools
    - git+https://github.com/aleju/imgaug.git
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - torchvision==0.15.2+cu118
